version: '3.1'

services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rocketpay_dev"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data